# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Cross-repo git worktree workspace manager (CLI / TUI)"
  homepage "https://github.com/tttpeng/grove"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.1/grove_darwin_amd64.tar.gz"
      sha256 "39521be950a1e3080a9e8fafc7ce2c3b856c71cb161647acee78a85fb3e41b1b"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.1/grove_darwin_arm64.tar.gz"
      sha256 "427de5b07c7ffc9fa0650d2d88b3c11442b8a417a43e13f263f20ac909adec2d"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.1/grove_linux_amd64.tar.gz"
      sha256 "9ffc28d3e3c41763ea1e182ecd60be9199129f3b3923e3e94886ebfa21b23650"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.1/grove_linux_arm64.tar.gz"
      sha256 "2a27db3428408c7c788251debe9f8a66738899b1e55b4fb3cf49393525c462e1"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  test do
    system "#{bin}/grove", "version"
  end
end
