# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Cross-repo git worktree workspace manager (CLI / TUI)"
  homepage "https://github.com/tttpeng/grove"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.0/grove_darwin_amd64.tar.gz"
      sha256 "a77aac949362895a0bd11bd1db400dc1f03335fbd0dea30f76804856ea6934e9"

      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.0/grove_darwin_arm64.tar.gz"
      sha256 "5e21ed397a1263e623a0ac10450a2f8c6c22371529deb4fcf425eb1930c4aa64"

      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.0/grove_linux_amd64.tar.gz"
      sha256 "08746d34e5f40049608c987109f3cb25e818656e10c5138408794545fd6ae9b9"
      define_method(:install) do
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tttpeng/grove/releases/download/v0.1.0/grove_linux_arm64.tar.gz"
      sha256 "ac3c540fd0914519051d674a1dd084a309c77e0093c3e5e8e4e3a0a94fef726e"
      define_method(:install) do
        bin.install "grove"
      end
    end
  end

  test do
    system "#{bin}/grove", "version"
  end
end
